export const CountryList = [
    "Antigua and Barbuda",
    "Argentina",
    "Australia",
    "Austria",
    "Bahamas",
    "Barbados",
    "Belgium",
    "Belize",
    "Benin",
    "Botswana",
    "Brazil",
    "Bulgaria",
    "Burundi",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chile",
    "China",
    "Colombia",
    "Congo",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czech Republic (Czechia)",
    "Côte d'Ivoire",
    "Denmark",
    "Dominican Republic",
    "DR Congo",
    "Ecuador",
    "Equatorial Guinea",
    "Eritrea",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guinea",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Kenya",
    "Liberia",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Maldives",
    "Malta",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Moldova",
    "Monaco",
    "Mozambique",
    "Namibia",
    "Netherlands",
    "New Zealand",
    "Nigeria",
    "Norway",
    "Panama",
    "Paraguay",
    "Peru",
    "Portugal",
    "Saint Kitts & Nevis",
    "Saint Lucia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Somalia",
    "South Africa",
    "South Korea",
    "Spain",
    "Sweden",
    "Switzerland",
    "Tanzania",
    "Thailand",
    "Togo",
    "Trinidad and Tobago",
    "Uganda",
    "United Kingdom",
    "United States",
    "Uruguay",
    "Venezuela",
    "Vietnam",
    "Zambia",
    "Zimbabwe"
  ];
